on:
  repository_dispatch
  
jobs:
  save_snapshot_job:
    runs-on: ubuntu-latest
    name: save snapshot
    steps:
    - name: echo client payload
      run: 'echo "Event text: ${{ github.event.client_payload }}"'
